name: Foodier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          node -v
          npm i -g pm2
          cd frontend
          npm i
          npm run build
          cd ..       
          ls
          cp -r frontend/build/. backend/build
          cp -r frontend/build/static/. backend/static
          ls
          cd backend
          pm2 kill
          python3 -m venv venv
          . venv/bin/activate
          pip install fastapi jinja2 toml cohere gunicorn
          pip install "uvicorn[standard]"
          ls
          pm2 start "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app" --name hello_world
